const mongoose = require('mongoose');

const schema = new mongoose.Schema({
    District_Name: String,
    UnitName: String,
    FIRNo: String,
    RI: String,
    Year: Number,
    Month: Number,
    Offence_From_Date: Date,
    Offence_To_Date: Date,
    FIR_Reg_DateTime: Date,
    FIR_Date: Date,
    FIR_Type: String,
    FIR_Stage: String,
    Complaint_Mode: String,
    CrimeGroup_Name: String,
    CrimeHead_Name: String,
    Latitude: Number,
    Longitude: Number,
    ActSection: String,
    IOName: String,
    KGID: String,
    IOAssigned_Date: Date,
    Internal_IO: String,
    Place_of_Offence: String,
    Distance_from_PS: Number,
    Beat_Name: String,
    Village_Area_Name: String,
    Male: Number,
    Female: Number,
    Boy: Number,
    Girl: Number,
    Age_0: Number,
    VICTIM_COUNT: Number,
    Accused_Count: Number,
    Arrested_Male: Number,
    Arrested_Female: Number,
    Arrested_Count: Number,
    Accused_ChargeSheeted_Count: Number,
    Conviction_Count: Number,
    FIR_ID: String,
    Unit_ID: String,
    Crime_No: String,
}, { timestamps: true });

module.exports = mongoose.model('CrimeRecord', schema);